import { createElement } from 'lwc';
import NewLwcFlow from 'c/newLwcFlow';

describe('c-new-lwc-flow', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-new-lwc-flow', {
            is: NewLwcFlow
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        const nameElement=element.shadowRoot.querySelector('.name');
        expect(nameElement.textContent).toBe('Dev');
        expect(1).toBe(1);
    });
});